config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :books, only: %i[index show] do
    resources :ownerships, only: %i[new create]
  end

  resources :ownerships, only: %i[index show new create destroy edit update] do
    resources :rentals, only: %i[new create]
  end

  resources :rentals, only: [:index, :update]

  namespace :owner do
    resources :rentals, only: [:index, :update]
  end

  resources :lists do
    resources :list_items, only: %i[create destroy]
  end

  post 'wishlist_list_items', to: 'list_items#create', as: 'wishlist_list_items'

  # Search route
  get '/search', to: 'search#index', as: 'search'

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_items, dependent: :destroy
  has_many :books, through: :list_items

  validates :name, presence: true, uniqueness: { scope: :user_id }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = current_user.lists
  end

  def show
    @list = List.find(params[:id])
    @list_items = @list.list_items
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      redirect_to @list, notice: 'List was created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, notice: 'List was deleted.', status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/index.html.erb
<div class="container">
  <% @lists.each do |list| %>
    <div class="list-section mb-5">
      <h2 class="text-center my-4 page-heading"><%= list.name %></h2>

      <% if list.name == "My Own Books" %>
        <div class="text-center">
          <%= link_to 'View All', ownerships_path, class: 'btn btn-info mb-3' %>
        </div>
      <% elsif list.name == "My Rentals" %>
        <div class="text-center">
          <%= link_to 'View All', rentals_path, class: 'btn btn-info mb-3' %>
        </div>
      <% elsif list.name == "Wishlist" %>
        <div class="text-center">
          <%= link_to 'View All', list_path(current_user.lists.find_by(name: 'Wishlist')), class: 'btn btn-info mb-3' %>
        </div>
      <% end %>

      <div class="container books-container">
        <% list.list_items.limit(4).each do |list_item| %>
          <div class="book-card">
            <div class="card mb-4 border-0 shadow">
              <a href="<%= book_path(list_item.book) %>">
                <img src="<%= list_item.book.cover_url %>" alt="Cover of <%= list_item.book.title %>" class="index-book-cover">
              </a>
              <div class="card-body card-body-index">
                <h5 class="card-title">
                  <strong><%= link_to list_item.book.title, book_path(list_item.book), class: 'text-dark' %></strong>
                </h5>
                <p class="card-text"><%= list_item.book.author %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<h1 class="text-center my-4 page-heading"><%= @list.name %></h1>

<div class="container d-flex gap-3 align-items-center flex-wrap">
  <% @list_items.each do |list_item| %>
    <div class="book-card">
      <div class="card mb-4 border-0 shadow">
        <a href="<%= book_path(list_item.book) %>">
          <img src="<%= list_item.book.cover_url %>" alt="Cover of <%= list_item.book.title %>" class="index-book-cover">
        </a>
        <div class="card-body card-body-wishlist">
          <h5 class="card-title">
            <strong><%= link_to list_item.book.title, book_path(list_item.book), class: 'text-dark' %></strong>
          </h5>
          <p class="card-text"><%= list_item.book.author %></p>
          <% unless @list.name == "My Rentals" %>
            <%= link_to list_list_item_path(@list, list_item), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-remove' do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>