config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :books, only: %i[index show] do
    resources :ownerships, only: %i[new create]
  end

  resources :ownerships, only: %i[index show new create destroy edit update] do
    resources :rentals, only: %i[new create]
  end

  resources :rentals, only: [:index, :update]

  namespace :owner do
    resources :rentals, only: [:index, :update]
  end

  resources :lists do
    resources :list_items, only: %i[create destroy]
  end

  post 'wishlist_list_items', to: 'list_items#create', as: 'wishlist_list_items'

  # Search route
  get '/search', to: 'search#index', as: 'search'

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flashes.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar justify-content-between px-3 navbar-expand-sm navbar-light navbar-lewagon">
  <!-- Brand logo and link to home page -->
  <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
    <i class="fas fa-book"></i>
    <span class="ms-2 header-title">Books2Book</span>
  <% end %>

  <!-- Search bar -->
  <form action="<%= books_path %>" method="get" class="form-inline d-flex align-items-center ms-3">
    <div class="input-group">
      <button class="btn" type="submit">Search</button>
      <input class="form-control" type="search" value="<%= params[:query] %>" placeholder="title, author, genre or ISBN" aria-label="Search" name="query">
    </div>
  </form>

  <!-- Toggle button for collapsed content in smaller screens -->
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links and dropdowns -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto">
      <% if user_signed_in? %>
        <!-- Wishlist link -->
        <li class="nav-item">
          <%= link_to "Wishlist", list_path(current_user.lists.find_by(name: 'Wishlist')), class: "nav-link" %>
        </li>

        <!-- My Books dropdown -->
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="myBooksDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Books
          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="myBooksDropdown">
            <%= link_to "Own", ownerships_path, class: "dropdown-item" %>
            <%= link_to "Offered", owner_rentals_path, class: "dropdown-item" %>
            <%= link_to "Rented", rentals_path, class: "dropdown-item" %>
          </div>
        </li>

        <!-- User profile and logout dropdown -->
        <li class="nav-item dropdown">
          <a href="#" class="avatar" id="profileDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://source.unsplash.com/random/?book", class: "avatar", alt: "dropdown menu" %>
          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="profileDropdown">
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <!-- Login link for non-signed-in users -->
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>