config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :books, only: %i[index show] do
    resources :ownerships, only: %i[new create]
  end

  resources :ownerships, only: %i[index show new create destroy edit update] do
    resources :rentals, only: %i[new create]
  end

  resources :rentals, only: [:index, :update]

  namespace :owner do
    resources :rentals, only: [:index, :update]
  end

  resources :lists do
    resources :list_items, only: %i[create destroy]
  end

  post 'wishlist_list_items', to: 'list_items#create', as: 'wishlist_list_items'

  # Search route
  get '/search', to: 'search#index', as: 'search'

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :ownerships
  has_many :rentals, through: :ownerships
  has_many :users, through: :ownerships
  has_many :list_items, dependent: :restrict_with_error
  has_many :lists, through: :list_items

  validates :title, :author, :genre, :description, :isbn, :cover_url, presence: true

  include PgSearch::Model
  pg_search_scope :search, against: [:title, :author, :genre, :isbn]
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:query].present?
      @books = Book.search(params[:query])
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/views/books/index.html.erb
<%# Title %>
<% if params[:query].present? %>
  <% if @books.size == 1 %>
    <h1 class="text-center my-4 page-heading">1 Result Found</h1>
  <% elsif @books.size == 0 %>
    <h1 class="text-center my-4 page-heading">No Result</h1>
  <% else %>
    <h1 class="text-center my-4 page-heading"><%= pluralize(@books.size, 'Result') %> Found</h1>
  <% end %>
<% else %>
  <h1 class="text-center my-4 page-heading">All Books</h1>
<% end %>

<%# Results %>
<div class="container d-flex gap-3 align-items-center flex-wrap">
  <% @books.each do |book| %>
    <div class="book-card">
      <div class="card mb-4 border-0 shadow">
        <a href="<%= book_path(book) %>">
          <img src="<%= book.cover_url %>" alt="Cover of <%= book.title %>" class="index-book-cover">
        </a>
        <div class="card-body card-body-index">
          <h5 class="card-title">
            <strong><%= link_to book.title, book_path(book), class: 'text-dark' %></strong>
          </h5>
          <p class="card-text"><%= book.author %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="container my-5">
  <div class="book-show card border-0 shadow">
    <div class="row no-gutters book-show-card">
      <div class="col-md-4 d-flex justify-content-center">
        <img src="<%= @book.cover_url %>" class="show-book-cover img-fluid" alt="<%= @book.title %> cover">
      </div>
      <div class="col-md-8">
        <div class="book-details card-body">
          <h1><%= @book.title %></h1>
          <p class="lead"><strong>Author:</strong> <%= @book.author %></p>
          <p class="lead"><%= @book.description %></p>
          <div class="row">
            <div class="col-md-4">
              <p><strong>Genre:</strong> <%= @book.genre %></p>
            </div>
            <div class="col-md-4">
              <p><strong>ISBN:</strong> <%= @book.isbn %></p>
            </div>
          </div>

          <div class="row">
          <div class="col-md-3">
          <%= button_to 'Add to Wishlist', wishlist_list_items_path(book_id: @book.id), method: :post, class: 'btn mt-3 wishlist-btn' %>
          </div>
          <div class="col-md-3">
          <%= link_to 'Rent out', new_book_ownership_path(@book), class: 'btn mt-3 wishlist-btn' %>
          </div>
          </div>

        </div>
      </div>
    </div>
  </div>
  <hr>
  <table class="table table-hover table-light">
    <thead>
      <tr>
        <th>Owner</th>
        <th>Condition</th>
        <th>Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @book.ownerships.each do |ownership| %>
        <tr>
          <td><%= ownership.user.first_name %> <%= ownership.user.last_name %></td>
          <td><%= ownership.condition %></td>
          <td>$<%= ownership.price %></td>
          <td>
            <%= link_to new_ownership_rental_path(ownership) do %>
              <button class="btn">Rent</button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>