config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :books, only: %i[index show] do
    resources :ownerships, only: %i[new create]
  end

  resources :ownerships, only: %i[index show new create destroy edit update] do
    resources :rentals, only: %i[new create]
  end

  resources :rentals, only: [:index, :update]

  namespace :owner do
    resources :rentals, only: [:index, :update]
  end

  resources :lists do
    resources :list_items, only: %i[create destroy]
  end

  post 'wishlist_list_items', to: 'list_items#create', as: 'wishlist_list_items'

  # Search route
  get '/search', to: 'search#index', as: 'search'

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/ownership.rb
class Ownership < ApplicationRecord
  has_many :rentals, dependent: :destroy
  belongs_to :book
  belongs_to :user

  validates :price, presence: true
  validates :condition, presence: true
  validates :book, presence: true

  CONDITIONS = ["Poor", "Fair", "Good", "Excellent", "Mint"]
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  def index
    @ownerships = current_user.ownerships.order(created_at: :desc)
    @ownership = Ownership.new
  end

  def show
    @ownership = Ownership.find(params[:id])
  end

  def new
    @book = Book.find(params[:book_id])
    @ownership = Ownership.new
  end

  def edit
    @ownership = Ownership.find(params[:id])
  end

  def update
    @ownership = Ownership.find(params[:id])
    if @ownership.update(ownership_params)
      redirect_to @ownership, notice: 'Ownership successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @book = Book.find_by(id: ownership_params[:book_id]) || Book.find(params[:book_id])
    if @book.nil?
      flash[:alert] = "Book not found"
      redirect_to ownerships_path and return
    end

    @ownership = @book.ownerships.find_or_initialize_by(user: current_user)

    if @ownership.new_record?
      @ownership.assign_attributes(ownership_params)
      if @ownership.save
        add_to_own_books_list(@ownership)
        redirect_to ownerships_path, notice: 'Ownership successfully created and added to My Own Books list.'
      else
        @book = @ownership.book
        render :new, status: :unprocessable_entity
      end
    else
      flash[:notice] = 'You already own this book.'
      redirect_to ownerships_path
    end
  end

  def destroy
    @ownership = Ownership.find(params[:id])
    remove_from_own_books_list(@ownership)
    @ownership.destroy
    redirect_to ownerships_path, notice: 'Ownership was successfully deleted.'
  end

  private

  def ownership_params
    params.require(:ownership).permit(:price, :condition, :book_id)
  end

  def add_to_own_books_list(ownership)
    own_books_list = current_user.lists.find_or_create_by(name: 'My Own Books')
    own_books_list.list_items.create(book: ownership.book)
  end

  def remove_from_own_books_list(ownership)
    own_books_list = current_user.lists.find_by(name: 'My Own Books')
    list_item = own_books_list.list_items.find_by(book: ownership.book)
    list_item.destroy if list_item.present?
  end
end

app/views/ownerships/_form.html.erb
<h1>Form to submit a new ownership</h1>

app/views/ownerships/edit.html.erb
<div class="container my-5">
  <div class="book-show card border-0 shadow">
    <div class="row no-gutters book-show-card">
      <div class="col-md-4 d-flex justify-content-center">
        <img src="<%= @ownership.book.cover_url %>" class="show-book-cover img-fluid" alt="<%= @ownership.book.title %> cover">
      </div>
      <div class="col-md-8">
        <div class="book-details card-body">
          <h1><%= @ownership.book.title %></h1>
          <p class="lead"><strong>Author:</strong> <%= @ownership.book.author %></p>
          <p class="lead"><i class="fa-solid fa-dollar-sign"></i>  <%= @ownership.price %></p>
          <p class="lead"><i class="fa-regular fa-square-check"></i>  <%= @ownership.condition %></p>
          <p class="lead"><%= @ownership.book.description %></p>
          <div class="row">
            <div class="col-md-4">
              <p><strong>Genre:</strong> <%= @ownership.book.genre %></p>
            </div>
            <div class="col-md-4">
              <p><strong>ISBN:</strong> <%= @ownership.book.isbn %></p>
            </div>
          </div>
          <div class="d-flex gap-2 mt-3">
            <button class="btn btn-secondary wishlist-btn" disabled>Return</button>
            <button class="btn btn-secondary wishlist-btn" disabled>Edit</button>
            <button class="btn btn-secondary wishlist-btn" disabled>Delete</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card p-4 mb-4">
    <%= simple_form_for @ownership do |f| %>
      <div class="form-group">
        <%= f.input :price, placeholder: "Enter a price for the book" %>
      </div>
      <div class="form-group">
        <%= f.input :condition, placeholder: "Enter a condition for the book", collection: Ownership::CONDITIONS %>
      </div>
      <%= f.submit 'Update', class: 'btn submit-btn' %>
    <% end %>
  </div>
</div>

app/views/ownerships/index.html.erb
<div class="container">
  <h1 class="text-center my-4 page-heading">My Own Books</h1>

  <p class="d-flex gap-1 justify-content-end">
    <button class="btn ml-4" type="button" data-bs-toggle="collapse" data-bs-target="#addOwnership" aria-expanded="false" aria-controls="addOwnership">
      Add Book
    </button>
  </p>
  <div class="collapse mb-4" id="addOwnership">
    <div class="container py-5">
      <div class="row">
        <div class="col-12 col-md-6 offset-lg-3">
          <div class="bg-white rounded p-3 shadow">
            <%= simple_form_for @ownership, url: ownerships_path do |f| %>
              <%= f.association :book, prompt: "Select a book" %>
              <%= f.input :price, placeholder: "Enter a price for the book" %>
              <%= f.input :condition, placeholder: "Enter a condition for the book", collection: Ownership::CONDITIONS %>
              <%= f.submit 'Create Offer', class: "btn btn-flat" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container d-flex gap-3 align-items-center flex-wrap">
    <% @ownerships.each do |ownership| %>
      <div class="book-card">
        <div class="card mb-4 border-0 shadow">
          <a href="<%= ownership_path(ownership) %>">
            <img src="<%= ownership.book.cover_url %>" alt="Cover of <%= ownership.book.title %>" class="index-book-cover">
          </a>
          <div class="card-body card-body-own-books">
            <h5 class="card-title">
              <strong><%= link_to ownership.book.title, book_path(ownership.book), class: 'text-dark' %></strong>
            </h5>
            <p class="card-text"><%= ownership.book.author %></p>
            <p class="card-text"><i class="fa-solid fa-dollar-sign"></i>  <%= ownership.price %></p>
            <p class="card-text"><i class="fa-regular fa-square-check"></i>  <%= ownership.condition %></p>
            <%= link_to ownership_path(ownership), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-remove' do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/ownerships/new.html.erb
<div class="container my-5">
  <div class="book-show card border-0 shadow">
    <div class="row no-gutters book-show-card">
      <div class="col-md-4 d-flex justify-content-center">
        <img src="<%= @book.cover_url %>" class="show-book-cover img-fluid" alt="<%= @book.title %> cover">
      </div>
      <div class="col-md-8">
        <div class="book-details card-body">
          <h1><%= @book.title %></h1>
          <p class="lead"><strong>Author:</strong> <%= @book.author %></p>
          <p class="lead"><%= @book.description %></p>
          <div class="row">
            <div class="col-md-4">
              <p><strong>Genre:</strong> <%= @book.genre %></p>
            </div>
            <div class="col-md-4">
              <p><strong>ISBN:</strong> <%= @book.isbn %></p>
            </div>
          </div>
          <button class="btn btn-secondary mt-3 wishlist-btn" disabled>Add to Wishlist</button>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <table class="table table-hover table-light">
    <thead>
      <tr>
        <th>Owner</th>
        <th>Condition</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <tr>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
    </tbody>
  </table>
  <div class="card p-4 mb-4">
    <%= simple_form_for [@book, @ownership] do |f| %>
      <div class="form-group">
        <%= f.input :price, placeholder: "Enter a price for the book" %>
      </div>
      <div class="form-group">
        <%= f.input :condition, placeholder: "Enter a condition for the book", collection: Ownership::CONDITIONS %>
      </div>
      <%= f.submit 'Create Offer', class: 'btn submit-btn' %>
    <% end %>
  </div>
</div>

app/views/ownerships/show.html.erb
<div class="container my-5">
  <div class="book-show card border-0 shadow">
    <div class="row no-gutters book-show-card">
      <div class="col-md-4 d-flex justify-content-center">
        <img src="<%= @ownership.book.cover_url %>" class="show-book-cover img-fluid" alt="<%= @ownership.book.title %> cover">
      </div>
      <div class="col-md-8">
        <div class="book-details card-body">
          <h1><%= @ownership.book.title %></h1>
          <p class="lead"><strong>Author:</strong> <%= @ownership.book.author %></p>
          <p class="lead"><i class="fa-solid fa-dollar-sign"></i>  <%= @ownership.price %></p>
          <p class="lead"><i class="fa-regular fa-square-check"></i>  <%= @ownership.condition %></p>
          <p class="lead"><%= @ownership.book.description %></p>
          <div class="row">
            <div class="col-md-4">
              <p><strong>Genre:</strong> <%= @ownership.book.genre %></p>
            </div>
            <div class="col-md-4">
              <p><strong>ISBN:</strong> <%= @ownership.book.isbn %></p>
            </div>
          </div>
          <div class="d-flex gap-2 mt-3">
            <%= link_to 'Back', ownerships_path, class: 'btn btn-secondary wishlist-btn' %>
            <%= link_to 'Edit', edit_ownership_path(@ownership), class: 'btn btn-secondary wishlist-btn' %>
            <%= link_to 'Delete', ownership_path(@ownership), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-secondary wishlist-btn' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>